---
server:
  port: 8888
security:
  basic:
    enabled: true 
  user:
    name: vind
    password: vind
management:
  security:
    enabled: false
spring:
  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}\git\config-repo
          search-paths:
            - service*