---
server:
  port: 8888
management:
  security:
    enabled: false
spring:
  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}\git\config-repo
          search-paths:
            - service*